<a href="https://colab.research.google.com/github/VikaLiubchenko/-/blob/main/%D0%9A%D0%BE%D0%BF%D1%96%D1%8F_%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D0%BD%D0%B8%D0%BA%D0%B0_%22HW1_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

# Завдання 1
Нехай m - число букв у вашому прізвищі, n - число букв у вашому імені. Наприклад, "Шевченко Тарас": m=8, n=5.

Представте у вигляді numpy масива матрицю

$$ A =
\begin{bmatrix}
m & 1 \\
0 & -n
\end{bmatrix}
$$

In [ ]:
m=8
n=8

A = np.array([[m,1],
              [0,-n]])

print(A)

[[ 8  1]
 [ 0 -8]]


# Завдання 2

Обчисліть визначник матриці $A$

In [ ]:
A = np.array([[8,1],
              [0,-8]])

det_A=np.linalg.det(A)

print(f"Визначник матриці А: {det_A}")

Визначник матриці А: -63.99999999999998


# Завдання 3

Знайдіть добуток $A^T \cdot B$, де $A^T$ отримана у результаті транспозиції матриці $A$,
$$
B = \begin{bmatrix}
1 & -n \\
n & 1
\end{bmatrix}
$$

In [ ]:
A = np.array([[8,1],
            [0,-8]])


A_T= A.transpose()
n=8
B = np.array([[1,-n],
              [n,1]])

result=np.dot(A_T, B)

print("Матриця A^T:")
print(A_T)
print("\nMатриця В:")
print(B)
print("\nДобуток A^T i B")
print(result)


Матриця A^T:
[[ 8  0]
 [ 1 -8]]

Mатриця В:
[[ 1 -8]
 [ 8  1]]

Добуток A^T i B
[[  8 -64]
 [-63 -16]]


# Завдання 4
Знайдіть добуток $A \mathbf{v}$, де
$$
\mathbf{v} =
\begin{bmatrix}
5 \\
-3
\end{bmatrix}
$$

In [ ]:
A = np.array([[8,1],
             [0,-8]])

v=np.array([5,-3])

result = np.dot(A,v)
print("Вектор v :")
print (v)
print("\nДобуток A* v :")
print(result)


Вектор v :
[ 5 -3]

Добуток A* v :
[37 24]


# Завдання 5
Обчислити середнє і стандартне відхилення колонки 'age' датафрейму data

In [ ]:
from seaborn import load_dataset
data = load_dataset('titanic')
data = data[data.index % A[0][0] == 0] # тут нічого не потрібно змінювати

In [ ]:
from seaborn import load_dataset

data = load_dataset('titanic')

A=np.array([[8,1],
            [0,-8]])

data=data[data.index % A[0][0]==0]

mean_age =data['age'].mean()
std_age=data['age'].std()

print(f"Середнє значення віку: {mean_age}")
print(f"Стандартне відхилення віку : {std_age}")

Середнє значення віку: 30.627906976744185
Стандартне відхилення віку : 14.73355235438759
